version: '3'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      API_KEY: "{{ cloudflare_api_key }}"
      ZONE: "{{ cloudflare_zone }}"
      SUBDOMAIN: "maple"
      PROXIED: "false"

  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: always
    networks:
      - traefik
    environment:
      CLOUDFLARE_EMAIL: "{{ cloudflare_email }}"
      CLOUDFLARE_DNS_API_TOKEN: "{{ cloudflare_api_key }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme_data:/acme_data/"
      - "{{ docker_compose_dir }}/config/traefik/traefik.yml:/traefik.yml"
      - "{{ docker_compose_dir }}/config/traefik/conf.d:/conf.d"

  agent:
    image: portainer/agent
    networks:
      - traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ee
    restart: always
    networks:
      - traefik
    command: -H tcp://agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data

  sablier:
    image: acouvreur/sablier:1.4.0
    restart: always
    networks:
      - traefik
    command:
      - start
      - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: always
    networks:
      - traefik
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_COOKIE_SECRET: '{{ oauth2_proxy.cookie_secret }}'
      OAUTH2_PROXY_COOKIE_DOMAINS: '.{{ domain_services }}' # Required so cookie can be read on all subdomains.
      OAUTH2_PROXY_WHITELIST_DOMAINS: '.{{ domain_services }}' # Required to allow redirection back to original requested target.

      # Configure to use GitHub
      OAUTH2_PROXY_PROVIDER: 'github'
      OAUTH2_PROXY_CLIENT_ID: '{{ oauth2_proxy.client_id }}'
      OAUTH2_PROXY_CLIENT_SECRET: '{{ oauth2_proxy.client_secret }}'
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_GITHUB_USER: '{{ oauth2_proxy.users }}'
      OAUTH2_PROXY_REDIRECT_URL: 'https://auth.{{ domain_services }}/oauth2/callback'
      OAUTH2_PROXY_SCOPE: "user:email"

      # Cookie options
      OAUTH2_PROXY_SESSION_STORE_TYPE: cookie
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: "true"
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: '24h'
      OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR: "/templates"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
    volumes:
      - "{{ docker_compose_dir }}/config/oauth2-proxy/templates:/templates:ro"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.route-authproxy.rule: (Host(`auth.{{ domain_services }}`) && PathPrefix(`/oauth2/`)) || (PathPrefix(`/oauth2/`))
      traefik.http.services.route-authproxy.loadbalancer.server.port: '4180'

volumes:
  portainer_data:
  acme_data:
networks:
  traefik:
