services:
{% if "minecraft-create-astral" in services %}
  minecraft-create-astral:
    container_name: mc-modpack
    image: itzg/minecraft-server:java17-alpine
    ports:
      - "25565:25565"
    volumes:
      - "{{ docker_dir }}/create-astral:/config"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: 0.14.14
      MEMORY: 4G
      USE_AIKAR_FLAGS: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
{% endif %}
{% if "minecraft-valhelsia-5" in services %}
  minecraft-valhelsia-5:
    container_name: mc-valhelsia-5
    image: amazoncorretto:17-alpine
    user: "1000:1000"
    ports:
      - "25565:25565"
    volumes:
      - "{{ docker_dir }}/minecraft/valhelsia5:/data:rw"
    command: [ "/data/ServerStart.sh" ]
    environment:
      MEMORY: 4G
    tty: true
    stdin_open: true
    restart: unless-stopped
{% endif %}
{% if "cloudflare-ddns" in services %}
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      API_KEY: "{{ cloudflare_api_key }}"
      ZONE: "offz.me"
      SUBDOMAIN: "maple"
      PROXIED: "false"
{% endif %}
