- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  pip:
    name: 
      - docker
      - docker-compose

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Create template directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item.path }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
  #    mode: '{{ item.mode }}'
  with_community.general.filetree: templates/
  when: item.state == 'directory'

- name: Copy templates to docker compose dir
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_dir }}/{{ item.path }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
  with_filetree: "templates/"
  when: item.state == 'file'

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
    remove_orphans: "{{ services_remove_orphans }}"


