http:
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

  routers:
    portainer:
      rule: Host(`portainer.{{domain_services}}`)
      service: "portainer"
