http:
  services:
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://filebrowser:80"

  routers:
    filebrowser:
      rule: Host(`files.{{domain_services}}`)
      entryPoints:
        - "websecure"
      middlewares:
        - sablier-filebrowser@file
      service: "filebrowser"
